### ISSUE TITLE
Menu icons missing on mobile

### ISSUE THREAD

**Issue by omnicons** [easymac/lounge-neuron#3] opened 2016-09-15 21:31 UTC
I've leave some screenshots here later, but as it stands on Chrome for Android if this theme is applied, all menu icons, including the settings icon that you'd need to change the theme back, disappear.

**Comment by omnicons** [comment] 2016-09-15 21:40
![alt text](http://i.imgur.com/CpTarLD.png)
![alt text](http://i.imgur.com/aZC7ayn.png)

**Comment by easymac** [comment] 2016-09-15 21:51
!!!

That's not good! I don't have an Android device to test with at the moment, but I'll try to reproduce the problem here & if I can't, I'll have an Android device available in an hour or so.

**Comment by omnicons** [comment] 2016-09-15 21:52
Thank you! I'll also have a look at it when I get off of work, If I fix it I'll just PR it and stuff. I just wanted to go ahead and let you know.

**Comment by easymac** [comment] 2016-09-15 22:01
I just pushed a commit to master that should fix this problem. I haven't tested on an Android device yet, however.

When you get a chance to give the new changes a try, let me know if it works.

Thanks for bringing this to my attention!

**Comment by easymac** [comment] 2016-09-15 22:07
I just got my hands on an Android device & it seems to be working as expected.

I guess I'll close this thread for now; please open more if you find other problems & let me know the fix isn't working on your device.

Thanks again!

**Closed as completed by easymac** 2016-09-15 22:07 UTC
